### ISSUE TITLE
error on patch

### ISSUE THREAD

**Issue by ucola** [vaimo/composer-patches#20] opened 2018-08-30 14:40 UTC
hi

we have an issue on composer

> Generating autoload files
> Processing patches configuration
> Nothing to patch
> PHP Fatal error:  Uncaught Error: Call to a member function setExtra() on array in /var/webroot/vendor/vaimo/composer-patches/src/Bootstrap.php:110
> Stack trace:
> #0 /var/webroot/vendor/vaimo/composer-patches/src/Plugin.php(65): Vaimo\ComposerPatches\Bootstrap->sanitizeLocker(Object(Composer\Package\Locker))
> #1 [internal function]: Vaimo\ComposerPatches\Plugin->postInstall(Object(Composer\Script\Event))
> #2 phar:///home/composer.phar/src/Composer/EventDispatcher/EventDispatcher.php(176): call_user_func(Array, Object(Composer\Script\Event))
> #3 phar:///home/composer.phar/src/Composer/EventDispatcher/EventDispatcher.php(96): Composer\EventDispatcher\EventDispatcher->doDispatch(Object(Composer\Script\Event))
> #4 phar:///home/composer.phar/src/Composer/Autoload/AutoloadGenerator.php(111): Composer\EventDispatcher\EventDispatcher->dispatchScript('pre-autoload-du...', true, Array, Array)
> #5 phar:///home/composer.phar/ in /var/webroot/vendor/vaimo/composer-patches/src/Bootstrap.php on line 110
> 
> Fatal error: Uncaught Error: Call to a member function setExtra() on array in /var/webroot/vendor/vaimo/composer-patches/src/Bootstrap.php:110
> Stack trace:
> #0 /var/webroot/vendor/vaimo/composer-patches/src/Plugin.php(65): Vaimo\ComposerPatches\Bootstrap->sanitizeLocker(Object(Composer\Package\Locker))
> #1 [internal function]: Vaimo\ComposerPatches\Plugin->postInstall(Object(Composer\Script\Event))
> #2 phar:///home/composer.phar/src/Composer/EventDispatcher/EventDispatcher.php(176): call_user_func(Array, Object(Composer\Script\Event))

did you know why?

**Comment by allanpaiste** [comment] 2018-09-04 16:16
Hello @ucola - any updates on this issue? Have you tried to repeat it with upgraded version of the module. I would still expect it to fail but with more verbose/targeted error message.

**Comment by allanpaiste** [comment] 2018-09-06 07:43
@ucola, any news on this issue? have you found out what exact package is causing this?

**Comment by ucola** [comment] 2018-09-06 07:44
We will try it next week again

**Comment by ucola** [comment] 2018-09-10 13:13
thank you for your answer, but we install the latest version and the issue appears always and we became no further infos...
we work with drupal, and we create a patch for the Composer.php file, because they don't delete all files from test Folder. The problem if we patch it with your module, the patch is apply but it dont work! if we use https://github.com/vaimo/composer-patches

our patch you see here: https://drupal-patch.soul.media/drupal8/core/composer_error-005.patch

**Comment by allanpaiste** [comment] 2018-09-10 20:38
The patch itself is not a problem here for sure. The issue is some package that should show up in the terminal/log when lock writing fails.

It would greatly help to get that log output when patches are being applied and a failure is encountered.

The failure should show up in the log as:

`Failed to locate package object for: <whatever the package names is>`

**Comment by allanpaiste** [comment] 2018-09-10 21:34
The lock manager's package resolver was rewritten in 4.4.1 and 3.35.1, I'd suggest trying on those versions. 

Overall it would still be really nice to know which package causes the error so getting the console log would greatly help. Is the project composer.json/composer.lock part of some private project or accessible publicly as well?

**Comment by allanpaiste** [comment] 2018-09-13 16:55
@ucola could you test applying the patches to the project with the latest versions (or with the versions I mention in my answer, whatever comes first :D). 

I will close the issue currently as I perceive it as addressed/fixed due to changing the whole logic on changing composer.lock to be based on much simpler logic that can not lead to errors like the one that you encountered. I will - however - gladly reopen it once it turns out that the issue that you encountered still persists.

**Closed** 2018-09-13 16:55 UTC
Labels: bug
